id: PE0063110
initial_creation_type: input
source_metadata:
  title: Sāṃkhyaparibhāṣā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Sāṃkhya
  data entry: Dhaval Patel
  contribution to GRETIL: Dhaval Patel
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:00:16.634068'
last_modified_at: '2022-03-09T15:00:16.634080'
